// CommonJS, every file is module (by default)
// Modules - Encapsulated Code (only sahre minimum)
const names = require("./4-names")
const sayHi = require("./5-utils")
const data = require('./6-alternative-flavor')
//console.log(names)
require("./7-mind-grenade")
sayHi ('Susan')
sayHi (names.John)
sayHi (names.Peter)